INSERT INTO users (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$e1zv4PUeNpbrbRYpJmk0euJnt5xNI0PGcYMxrSX8t6kJrAmOZSS/S');
INSERT INTO users (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$e1zv4PUeNpbrbRYpJmk0euJnt5xNI0PGcYMxrSX8t6kJrAmOZSS/S');

INSERT INTO roles (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO roles (authority) VALUES ('ROLE_ADMIN');

INSERT INTO user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO categories(name,created_At) VALUES ('Telefones',Now());
INSERT INTO categories(name,created_At) VALUES ('Eletrônicos',Now());
INSERT INTO categories(name,created_At) VALUES ('Computadores',Now());
INSERT INTO categories(name,created_At) VALUES ('Livros',Now());
INSERT INTO categories(name,created_At) VALUES ('Novidades',Now());
INSERT INTO categories(name,created_At) VALUES ('Em promoção',Now());
insert into products (name, description, price, img_url, created_at, date) values ('Lemon Garlic Marinade', 'A zesty marinade made with lemon juice and garlic, ideal for chicken or fish.', 91.47, 'http://dummyimage.com/230x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Kids'' Science Experiment Kit', 'Engaging kit with science experiments for children.', 241.83, 'http://dummyimage.com/203x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Kombucha Drink', 'Refreshing and tangy fermented tea, available in various flavors.', 204.09, 'http://dummyimage.com/232x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Blackberry Compote', 'Sweet blackberry compote, perfect for topping desserts.', 107.67, 'http://dummyimage.com/142x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Garlic Herb Seasoning', 'A blend of herbs and garlic for seasoning meats and vegetables.', 275.59, 'http://dummyimage.com/228x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Deep Tissue Massage Gun', 'Rechargeable massage gun for relieving muscle soreness.', 333.84, 'http://dummyimage.com/102x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Almond Joy Munch Bars', 'A delightful mix of chocolate, coconut, and almonds in a snack bar.', 165.97, 'http://dummyimage.com/127x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Dog Collar', 'Adjustable dog collar with personalized tags.', 282.41, 'http://dummyimage.com/154x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Handmade Soap Making Kit', 'Complete kit for crafting your own scented soaps.', 95.67, 'http://dummyimage.com/190x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Sustainable Wooden Toys', 'Eco-friendly toys for learning and imaginative play.', 96.73, 'http://dummyimage.com/218x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Wall-Mounted Spice Rack', 'Space-saving rack to store and organize spices conveniently.', 253.93, 'http://dummyimage.com/196x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Nutritional Yeast', 'A healthy vegan cheese alternative packed with nutrients and flavor.', 304.88, 'http://dummyimage.com/165x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Spinach and Cheese Quiche', 'Savory quiche loaded with spinach and cheese.', 29.6, 'http://dummyimage.com/105x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Home Karaoke System', 'Complete karaoke system with microphones and speakers.', 304.03, 'http://dummyimage.com/115x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Smoked Salmon', 'Deliciously smoked salmon, great for bagels.', 177.43, 'http://dummyimage.com/236x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Organic Brown Rice Cakes', 'Light and crunchy rice cakes made from organic brown rice.', 229.19, 'http://dummyimage.com/203x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Raspberry Tart', 'A delicious tart filled with fresh raspberry filling.', 145.06, 'http://dummyimage.com/211x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Wireless Gaming Mouse', 'Ergonomic mouse designed for gamers with high DPI.', 26.97, 'http://dummyimage.com/151x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Cold Brew Coffee Concentrate', 'Rich and smooth cold brew coffee concentrate, just add water or milk.', 149.98, 'http://dummyimage.com/213x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Buffalo Chicken Wraps', 'Savory wraps with buffalo chicken and fresh vegetables.', 206.34, 'http://dummyimage.com/140x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Electric Razor', 'Rechargeable electric razor for a smooth shave.', 266.46, 'http://dummyimage.com/160x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Linen Trousers', 'Breathable linen trousers perfect for hot weather.', 267.13, 'http://dummyimage.com/215x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Couscous', 'Quick-cooking couscous, great as a side or base.', 166.03, 'http://dummyimage.com/246x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Smart Water Bottle with Hydration Reminder', 'Bottle that tracks your water intake and reminds you to drink.', 125.24, 'http://dummyimage.com/169x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Savory Snack Mix', 'A mix of nuts, pretzels, and crackers, seasoned just right for snacking.', 114.19, 'http://dummyimage.com/100x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Cranberry Orange Oatmeal', 'Instant oatmeal flavored with cranberries and orange zest for breakfast.', 305.44, 'http://dummyimage.com/186x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Nut Mix', 'A blend of mixed nuts for snacking.', 31.32, 'http://dummyimage.com/157x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Turkey Bacon', 'Delicious turkey bacon, a healthier alternative.', 78.57, 'http://dummyimage.com/118x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Pet Hair Vacuum Cleaner Attachment', 'Specialized attachment for removing pet hair from surfaces.', 226.09, 'http://dummyimage.com/131x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Smart LED Light Strip', 'Customizable RGB LED light strip, perfect for mood lighting.', 188.5, 'http://dummyimage.com/102x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Frozen Fruit Medley', 'A mix of strawberries, blueberries, and raspberries, perfect for smoothies.', 244.17, 'http://dummyimage.com/153x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Incense Holder', 'Ceramic incense holder for a calming atmosphere.', 133.13, 'http://dummyimage.com/194x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Almond Butter Cups', 'Rich chocolate cups filled with almond butter, a delicious treat.', 176.53, 'http://dummyimage.com/220x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Raspberry Lemonade Mix', 'A refreshing drink mix that combines sweet raspberries and tart lemons, perfect for summer.', 238.96, 'http://dummyimage.com/202x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Granola', 'Crunchy and flavorful mix of oats and honey.', 265.7, 'http://dummyimage.com/153x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Cotton Sweatpants', 'Soft and breathable cotton sweatpants perfect for lounging or workouts.', 115.4, 'http://dummyimage.com/200x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Peanut Butter', 'Creamy and smooth peanut butter, perfect for sandwiches.', 115.99, 'http://dummyimage.com/198x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Organic Quinoa Salad', 'A refreshing salad made with quinoa and seasonal veggies.', 130.74, 'http://dummyimage.com/245x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Oven-Baked Parmesan Zucchini', 'Frozen zucchini slices coated in parmesan cheese, perfect for baking or frying.', 198.32, 'http://dummyimage.com/117x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Home Delivery Food Journal', 'Track your meals and nutrition with this handy food journal.', 96.18, 'http://dummyimage.com/166x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Ceramic Cookware Set', 'Durable and non-stick ceramic cookware for healthy cooking.', 123.99, 'http://dummyimage.com/163x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Roasted Garlic Mashed Potatoes', 'Creamy mashed potatoes infused with roasted garlic flavor.', 335.84, 'http://dummyimage.com/191x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Electric Stool Heater', 'Heated stool cover for extra comfort during winter.', 56.13, 'http://dummyimage.com/156x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Garlic and Herb Rub', 'A seasoning blend of garlic and herbs to enhance any dish.', 299.59, 'http://dummyimage.com/183x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Vegetable Spring Rolls', 'Crispy spring rolls filled with vegetables', 254.68, 'http://dummyimage.com/101x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Peanut Butter Protein Balls', 'No-bake energy bites made with peanut butter and oats.', 255.75, 'http://dummyimage.com/116x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Pet Reflective Vest', 'Safety vest for pets during nighttime walks.', 38.71, 'http://dummyimage.com/114x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Frozen Edamame', 'Lightly salted frozen edamame, a protein-packed snack.', 237.04, 'http://dummyimage.com/225x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Maple Almond Yogurt', 'Creamy yogurt made with maple and almond flavors.', 150.82, 'http://dummyimage.com/202x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Cat Scratching Post with Toys', 'Multi-level scratching post to keep your cat entertained.', 22.88, 'http://dummyimage.com/127x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Chocolate Mint Protein Shake', 'A nutritious shake with rich chocolate and refreshing mint flavors.', 133.15, 'http://dummyimage.com/240x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Yoga Strap', 'Durable yoga strap for deeper stretches.', 96.64, 'http://dummyimage.com/211x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Solar String Lights', 'Eco-friendly string lights for outdoor decor.', 339.22, 'http://dummyimage.com/247x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Caraway Rye Bread', 'Artisan bread with caraway seeds for added flavor.', 314.47, 'http://dummyimage.com/134x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Almond Quinoa Salad', 'Healthy salad made with quinoa, almonds, and mixed greens, perfect for a light meal.', 334.95, 'http://dummyimage.com/170x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Woven Storage Baskets', 'Stylish baskets for organizing various items in your home.', 36.31, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Mango Salsa', 'Fresh mango salsa with a hint of lime for a zesty topping.', 234.94, 'http://dummyimage.com/126x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Silicone Baking Mat Set', 'Non-stick and reusable mats for easy baking.', 175.22, 'http://dummyimage.com/247x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Couscous', 'Quick-cooking couscous, great as a side or base.', 175.32, 'http://dummyimage.com/112x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Chopping Board', 'Reversible bamboo chopping board for food prep.', 146.1, 'http://dummyimage.com/155x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Portable Electric Fan', 'Compact fan for personal cooling at work or home.', 70.2, 'http://dummyimage.com/126x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Noise Reduction Headphones', 'Passive noise reduction headphones for focus.', 88.08, 'http://dummyimage.com/123x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Adjustable Standing Desk', 'Ergonomic desk that adjusts height for standing or sitting.', 244.95, 'http://dummyimage.com/130x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Caramelized Onion Dip', 'Creamy dip made with caramelized onions, perfect for chips or veggies.', 124.75, 'http://dummyimage.com/127x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Weighted Blanket', 'Therapeutic weighted blanket for better sleep.', 120.35, 'http://dummyimage.com/155x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('3D Night Light', 'Color-changing 3D night light for kids'' rooms.', 53.13, 'http://dummyimage.com/193x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Gaming Mousepad', 'Oversized gaming mousepad with smooth surface.', 219.85, 'http://dummyimage.com/234x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Vegetable Lasagna', 'Layers of pasta, veggies, and cheese baked to perfection.', 79.57, 'http://dummyimage.com/195x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Noise Cancelling Ear Muffs', 'Ear protection for shooting and industrial use.', 18.61, 'http://dummyimage.com/180x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Suede Ankle Booties', 'Chic suede ankle booties, perfect for dressing up or down.', 308.86, 'http://dummyimage.com/184x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Ultraviolet Phone Sanitizer', 'UV sanitizer that kills germs on your smartphone.', 122.95, 'http://dummyimage.com/236x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Spice Rack', 'Rotating spice rack with 20 spice jars.', 32.43, 'http://dummyimage.com/208x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Organic Green Apples', 'Fresh and tart organic green apples, great for snacking or baking.', 200.19, 'http://dummyimage.com/119x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Zucchini Noodle Pasta', 'Low-carb zucchini noodles, perfect for a healthy alternative to pasta.', 167.4, 'http://dummyimage.com/183x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Marinated Artichokes', 'Artichoke hearts marinated in herbs and oil.', 338.31, 'http://dummyimage.com/139x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Dried Cranberries', 'Sweet and tart dried cranberries, great for salads and baking.', 38.44, 'http://dummyimage.com/209x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Frozen Burritos', 'Easy-to-heat frozen burritos for a quick meal.', 228.92, 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Adjustable Yoga Mat Strap', 'Convenient strap for carrying yoga mats to class.', 245.03, 'http://dummyimage.com/164x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Foldable Yoga Mat Carry Bag', 'Durable bag for carrying your yoga mat and accessories.', 87.0, 'http://dummyimage.com/149x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Portable Air Conditioner', 'Compact air conditioner for personal cooling.', 247.69, 'http://dummyimage.com/155x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Paint By Numbers Kit', 'Relaxing paint kit with pre-printed canvas for painting.', 225.55, 'http://dummyimage.com/155x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Ceramic Cookware Set', 'Durable and non-stick ceramic cookware for healthy cooking.', 126.08, 'http://dummyimage.com/164x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Lentil Pasta', 'Gluten-free pasta made from lentils, high in protein.', 198.94, 'http://dummyimage.com/149x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Compressed Towel Tablets', 'Compact towels that expand when wet, ideal for travel.', 16.54, 'http://dummyimage.com/173x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Magnetic Spice Jars', 'Convenient magnetic jars for easy spice storage.', 272.67, 'http://dummyimage.com/108x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Chickpea Pancakes', 'Savory pancakes made with chickpea flour, high in protein.', 18.62, 'http://dummyimage.com/180x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Sweet and Spicy Barbecue Sauce', 'A flavorful barbecue sauce with a sweet and spicy kick.', 302.59, 'http://dummyimage.com/135x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Underwater Camera', 'Waterproof camera for capturing underwater adventures.', 261.13, 'http://dummyimage.com/237x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Tattoo Kit', 'Complete tattoo kit for beginners and professionals.', 215.72, 'http://dummyimage.com/191x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Collapsible Folding Chair', 'Lightweight and portable chair for camping or events.', 175.21, 'http://dummyimage.com/180x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Honey Graham Crackers', 'Sweet and crunchy honey-flavored graham crackers.', 98.84, 'http://dummyimage.com/238x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Vacuum Sealer Machine', 'Seal food and maintain freshness longer.', 299.3, 'http://dummyimage.com/142x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Electric Heating Pad', 'Microwaveable heating pad for muscle pain relief and relaxation.', 137.42, 'http://dummyimage.com/147x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Bock Beer Mustard', 'Flavorful mustard with a tangy kick, perfect for hot dogs and sandwiches.', 123.01, 'http://dummyimage.com/119x100.png/ff4444/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Chili Lime Corn Chips', 'Crunchy corn chips flavored with chili and lime for a zesty kick.', 51.72, 'http://dummyimage.com/166x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Tuscan Bean Soup', 'A hearty mix of beans in a flavorful tomato broth.', 100.43, 'http://dummyimage.com/197x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Blackberry Jam', 'Delicious homemade style blackberry jam.', 144.81, 'http://dummyimage.com/117x100.png/dddddd/000000',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Organic Quinoa', 'Nutritious organic quinoa for salads or sides', 97.41, 'http://dummyimage.com/114x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Pineapple Chunks (canned)', 'Sweet pineapple chunks in syrup.', 277.11, 'http://dummyimage.com/122x100.png/cc0000/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');
insert into products (name, description, price, img_url, created_at, date) values ('Car Vacuum', 'Portable car vacuum cleaner with strong suction.', 79.25, 'http://dummyimage.com/126x100.png/5fa2dd/ffffff',Now(),TIMESTAMP WITH TIME ZONE '2025-02-26T10:00:00Z');

insert into product_category (product_id, category_id) values (1, 3);
insert into product_category (product_id, category_id) values (2, 4);
insert into product_category (product_id, category_id) values (3, 4);
insert into product_category (product_id, category_id) values (4, 3);
insert into product_category (product_id, category_id) values (5, 1);
insert into product_category (product_id, category_id) values (6, 4);
insert into product_category (product_id, category_id) values (7, 1);
insert into product_category (product_id, category_id) values (8, 3);
insert into product_category (product_id, category_id) values (9, 2);
insert into product_category (product_id, category_id) values (10, 1);
insert into product_category (product_id, category_id) values (11, 3);
insert into product_category (product_id, category_id) values (12, 1);
insert into product_category (product_id, category_id) values (13, 4);
insert into product_category (product_id, category_id) values (14, 3);
insert into product_category (product_id, category_id) values (15, 1);
insert into product_category (product_id, category_id) values (16, 3);
insert into product_category (product_id, category_id) values (17, 1);
insert into product_category (product_id, category_id) values (18, 4);
insert into product_category (product_id, category_id) values (19, 2);
insert into product_category (product_id, category_id) values (20, 3);
insert into product_category (product_id, category_id) values (21, 3);
insert into product_category (product_id, category_id) values (22, 4);
insert into product_category (product_id, category_id) values (23, 4);
insert into product_category (product_id, category_id) values (24, 3);
insert into product_category (product_id, category_id) values (25, 3);
insert into product_category (product_id, category_id) values (26, 1);
insert into product_category (product_id, category_id) values (27, 1);
insert into product_category (product_id, category_id) values (28, 4);
insert into product_category (product_id, category_id) values (29, 3);
insert into product_category (product_id, category_id) values (30, 3);
insert into product_category (product_id, category_id) values (31, 4);
insert into product_category (product_id, category_id) values (32, 4);
insert into product_category (product_id, category_id) values (33, 3);
insert into product_category (product_id, category_id) values (34, 3);
insert into product_category (product_id, category_id) values (35, 2);
insert into product_category (product_id, category_id) values (36, 2);
insert into product_category (product_id, category_id) values (37, 4);
insert into product_category (product_id, category_id) values (38, 2);
insert into product_category (product_id, category_id) values (39, 2);
insert into product_category (product_id, category_id) values (40, 4);
insert into product_category (product_id, category_id) values (41, 3);
insert into product_category (product_id, category_id) values (42, 3);
insert into product_category (product_id, category_id) values (43, 2);
insert into product_category (product_id, category_id) values (44, 2);
insert into product_category (product_id, category_id) values (45, 2);
insert into product_category (product_id, category_id) values (46, 1);
insert into product_category (product_id, category_id) values (47, 1);
insert into product_category (product_id, category_id) values (48, 1);
insert into product_category (product_id, category_id) values (49, 1);
insert into product_category (product_id, category_id) values (50, 4);
insert into product_category (product_id, category_id) values (51, 2);
insert into product_category (product_id, category_id) values (52, 4);
insert into product_category (product_id, category_id) values (53, 2);
insert into product_category (product_id, category_id) values (54, 4);
insert into product_category (product_id, category_id) values (55, 3);
insert into product_category (product_id, category_id) values (56, 1);
insert into product_category (product_id, category_id) values (57, 3);
insert into product_category (product_id, category_id) values (58, 1);
insert into product_category (product_id, category_id) values (59, 4);
insert into product_category (product_id, category_id) values (60, 4);
insert into product_category (product_id, category_id) values (61, 1);
insert into product_category (product_id, category_id) values (62, 4);
insert into product_category (product_id, category_id) values (63, 2);
insert into product_category (product_id, category_id) values (64, 2);
insert into product_category (product_id, category_id) values (65, 3);
insert into product_category (product_id, category_id) values (66, 3);
insert into product_category (product_id, category_id) values (67, 2);
insert into product_category (product_id, category_id) values (68, 4);
insert into product_category (product_id, category_id) values (69, 1);
insert into product_category (product_id, category_id) values (70, 2);
insert into product_category (product_id, category_id) values (71, 4);
insert into product_category (product_id, category_id) values (72, 4);
insert into product_category (product_id, category_id) values (73, 1);
insert into product_category (product_id, category_id) values (74, 1);
insert into product_category (product_id, category_id) values (75, 2);
insert into product_category (product_id, category_id) values (76, 2);
insert into product_category (product_id, category_id) values (77, 2);
insert into product_category (product_id, category_id) values (78, 1);
insert into product_category (product_id, category_id) values (79, 4);
insert into product_category (product_id, category_id) values (80, 3);
insert into product_category (product_id, category_id) values (81, 4);
insert into product_category (product_id, category_id) values (82, 4);
insert into product_category (product_id, category_id) values (83, 3);
insert into product_category (product_id, category_id) values (84, 3);
insert into product_category (product_id, category_id) values (85, 3);
insert into product_category (product_id, category_id) values (86, 2);
insert into product_category (product_id, category_id) values (87, 4);
insert into product_category (product_id, category_id) values (88, 4);
insert into product_category (product_id, category_id) values (89, 1);
insert into product_category (product_id, category_id) values (90, 2);
insert into product_category (product_id, category_id) values (91, 2);
insert into product_category (product_id, category_id) values (92, 2);
insert into product_category (product_id, category_id) values (93, 3);
insert into product_category (product_id, category_id) values (94, 1);
insert into product_category (product_id, category_id) values (95, 2);
insert into product_category (product_id, category_id) values (96, 1);
insert into product_category (product_id, category_id) values (97, 2);
insert into product_category (product_id, category_id) values (98, 4);
insert into product_category (product_id, category_id) values (99, 2);
insert into product_category (product_id, category_id) values (100, 2);
insert into product_category (product_id, category_id) values (74, 5);
insert into product_category (product_id, category_id) values (15, 5);
insert into product_category (product_id, category_id) values (49, 5);
insert into product_category (product_id, category_id) values (39, 5);
insert into product_category (product_id, category_id) values (65, 5);
insert into product_category (product_id, category_id) values (29, 5);
insert into product_category (product_id, category_id) values (2, 5);
insert into product_category (product_id, category_id) values (47, 5);
insert into product_category (product_id, category_id) values (4, 5);
insert into product_category (product_id, category_id) values (14, 5);
insert into product_category (product_id, category_id) values (5, 5);
insert into product_category (product_id, category_id) values (21, 5);
insert into product_category (product_id, category_id) values (64, 5);
insert into product_category (product_id, category_id) values (27, 5);
insert into product_category (product_id, category_id) values (41, 5);

insert into product_category (product_id, category_id) values (43, 6);
insert into product_category (product_id, category_id) values (13, 6);
insert into product_category (product_id, category_id) values (60, 6);
insert into product_category (product_id, category_id) values (40, 6);
insert into product_category (product_id, category_id) values (49, 6);
insert into product_category (product_id, category_id) values (64, 6);
insert into product_category (product_id, category_id) values (28, 6);
insert into product_category (product_id, category_id) values (4, 6);
insert into product_category (product_id, category_id) values (66, 6);
insert into product_category (product_id, category_id) values (8, 6);
insert into product_category (product_id, category_id) values (5, 6);
insert into product_category (product_id, category_id) values (37, 6);
insert into product_category (product_id, category_id) values (62, 6);
insert into product_category (product_id, category_id) values (22, 6);
insert into product_category (product_id, category_id) values (12, 6);



